# CONSTANTS
WIDTH,HEIGHT = 800, 800
ROWS,COLUMNS = 8,8
ROW_GAP, COLUMN_GAP = HEIGHT // ROWS, WIDTH // COLUMNS
SQUARE_SIZE = WIDTH//COLUMNS
DIFFICULTY = 4
MINIMUM = -999999
MAXIMUM = 999999

# COLOR PIECES
BLACK = "black"
WHITE = "white"
BLUE = "blue"
ASSIST = "assist"
YELLOW = "yellow"
ORANGE = "orange"
HIGHLIGHT = "highlight"

# BACKGROUND COLOR
BACKGROUND = "green"

# Directions
UP,DOWN,RIGHT,LEFT,UP_RIGHT,DOWN_RIGHT,DOWN_LEFT,UP_LEFT = (0,-1),(0,1),(1,0),(-1,0),(1,-1),(1,1),(-1,1),(-1,-1)
DIRECTIONS = [UP,DOWN,RIGHT,LEFT,UP_RIGHT,DOWN_RIGHT,DOWN_LEFT,UP_LEFT]